### ISSUE TITLE
Symfony 4: "Legacy deprecation notices (1)" because of this bundle

### ISSUE THREAD

**Issue by TomaszGasior** [dmaicher/doctrine-test-bundle#79]
After installation of this bundle, message "Legacy deprecation notices (1)" is shown always in output of `bin/phpunit` command.

I prepared minimal project which reproduces this issue. 
[skeleton.zip](https://github.com/dmaicher/doctrine-test-bundle/files/3026132/skeleton.zip) Please unzip it and try to run `bin/phpunit`.

**Comment by dmaicher** [comment]
Seems this happens when running PHPUnit 6.4+ but < 7.

This class was deprecated in PHPUnit 6.4 :stuck_out_tongue: 

https://github.com/sebastianbergmann/phpunit/blob/6.4.0/src/Framework/BaseTestListener.php#L15

This will be tricky to fix and PHPUnit v6 is legacy anyway :wink: 

If you use PHPUnit 7 (or even 8 with the Extension and not the Listener) then you are deprecation-free :wink: 

```
it@9f5f598bd915:/var/www/skeleton  $ export SYMFONY_PHPUNIT_VERSION=7.5 && bin/phpunit
#!/usr/bin/env php
PHPUnit 7.5.8 by Sebastian Bergmann and contributors.

Testing Project Test Suite
.                                                                   1 / 1 (100%)

Time: 29 ms, Memory: 4.00 MB

OK (1 test, 1 assertion)
```
