### ISSUE TITLE
Drop support for PHPUnit 6?

### ISSUE THREAD

**Issue by dmaicher** [dmaicher/doctrine-test-bundle#81]
We should consider dropping support for PHPUnit 6 with the build-in listener.

Its not supported anymore: https://phpunit.de/supported-versions.html

Also when using PHPUnit 6.4+ but < 7 there are deprecations: https://github.com/dmaicher/doctrine-test-bundle/issues/79

I don't think its worth fixing them for this legacy version of PHPUnit.

If we move forward this should be released as a new major release as it would be a BC break for people using PHPUnit 6.

@garak @mnapoli @B-Galati what do you think?

**Comment by mnapoli** [comment]
@dmaicher honestly you should do what's simplest for you to maintain. Existing releases will still work anyway for those still on v6.

Also technically I'm not sure this is a BC break since Composer will deal with version constraints and won't install new updates for people on PHPUnit 6. But it's up to you, sometimes doing a BC break is clearer for users.

**Comment by dmaicher** [comment]
@mnapoli actually it will be a BC break as this bundle does not have hard dependency on phpunit (so it works with symfony's phpunit bridge as well for example).

Maybe I could add a "conflicts" for phpunit 6 though.

**Comment by B-Galati** [comment]
New major that supports only PhpUnit 7+ sounds good to me.

Given the stability of this library, current version can stay unmaintained IMHO once the new major is released .

**Comment by B-Galati** [comment]
Perhaps there is some work to do at runtime to detect Symfony phpunit bridge version that woul not be compatible.
